name: ARM Build
on: push
jobs:
  test_suite:
    name: Setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [armv6l, arm64]
        include:
        - target: armv6l
          cpu: cortex-a7
          cpu_info: cpuinfo/raspberrypi_3b
          base_image: https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2023-05-03/2023-05-03-raspios-bullseye-armhf.img.xz
        - target: arm64
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_4b
          base_image: https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2023-05-03/2023-05-03-raspios-bullseye-arm64.img.xz
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: ARM Runner
      uses: pguyot/arm-runner-action@v2
      with:
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 16384
        optimize_image: no
        commands: |
          sudo apt install -y git upx tar bzip2 golang
          ls -al
          echo 0 $PWD
          echo 1
          git tag -l
          echo 2
          git tag -l|grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$'
          echo 3
          git tag -l|grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$'|sort -r -V
          echo 4
          git tag -l|grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$'|sort -r -V|head -1
          go version
          go env

          #|grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$'|sort -r -V|head -1
#          ./contrib/go-setup.sh
#          export PATH=$PATH:/usr/local/go/bin
#          go version
#          go env
#          ./build-release.sh -r -N -x
