name: ARM Build
on: push
jobs:
  test_suite:
    name: Setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [arm64]
        include:
#        - target: armv6l
#          cpu: arm1176
#          cpu_info: cpuinfo/raspberrypi_zero2_w
#          base_image: raspios_lite:latest
        - target: arm64
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          base_image: raspios_lite_arm64:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: ARM Runner
      uses: pguyot/arm-runner-action@v2
      with:
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 4096
        optimize_image: no
        commands: |
          sudo apt install git
          ./contrib/go-setup.sh
          export PATH=$PATH:/usr/local/go/bin
          go version
          go env
          ./build-release.sh -x -r -n
