name: ARM Build
on: push
jobs:
  test_suite:
    name: Setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero_raspbian, zero_raspios, zero_dietpi, zero2_64_raspios]
        include:
        - target: zero_raspbian
          cpu: arm1176
          cpu_info: cpuinfo/raspberrypi_zero_w
          base_image: raspbian_lite:latest
        - target: zero_raspios
          cpu: arm1176
          cpu_info: cpuinfo/raspberrypi_zero_w
          base_image: raspios_lite:latest
        - target: zero_dietpi
          cpu: arm1176
          cpu_info: cpuinfo/raspberrypi_zero_w
          base_image: dietpi:rpi_armv6_bullseye
        - target: zero2_64_raspios
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          base_image: raspios_lite_arm64:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: ARM Runner
      uses: pguyot/arm-runner-action@v2
      with:
        image_additional_mb: 4096
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        optimize_image: no
        commands: |
          uname -a
          uname -m
          ./contrib/go-setup.sh
